// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recommed_rpc.proto

package RecommendPro

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecommendReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecommendReq) Reset()         { *m = RecommendReq{} }
func (m *RecommendReq) String() string { return proto.CompactTextString(m) }
func (*RecommendReq) ProtoMessage()    {}
func (*RecommendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_721ac0927679af21, []int{0}
}

func (m *RecommendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendReq.Unmarshal(m, b)
}
func (m *RecommendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendReq.Marshal(b, m, deterministic)
}
func (m *RecommendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendReq.Merge(m, src)
}
func (m *RecommendReq) XXX_Size() int {
	return xxx_messageInfo_RecommendReq.Size(m)
}
func (m *RecommendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendReq proto.InternalMessageInfo

func (m *RecommendReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RecommendReply struct {
	RecommendItem        []*RecommendItem `protobuf:"bytes,1,rep,name=recommendItem,proto3" json:"recommendItem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RecommendReply) Reset()         { *m = RecommendReply{} }
func (m *RecommendReply) String() string { return proto.CompactTextString(m) }
func (*RecommendReply) ProtoMessage()    {}
func (*RecommendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_721ac0927679af21, []int{1}
}

func (m *RecommendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendReply.Unmarshal(m, b)
}
func (m *RecommendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendReply.Marshal(b, m, deterministic)
}
func (m *RecommendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendReply.Merge(m, src)
}
func (m *RecommendReply) XXX_Size() int {
	return xxx_messageInfo_RecommendReply.Size(m)
}
func (m *RecommendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendReply.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendReply proto.InternalMessageInfo

func (m *RecommendReply) GetRecommendItem() []*RecommendItem {
	if m != nil {
		return m.RecommendItem
	}
	return nil
}

type RecommendItem struct {
	MoiveId              int32    `protobuf:"varint,1,opt,name=moiveId,proto3" json:"moiveId,omitempty"`
	Rating               float32  `protobuf:"fixed32,2,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecommendItem) Reset()         { *m = RecommendItem{} }
func (m *RecommendItem) String() string { return proto.CompactTextString(m) }
func (*RecommendItem) ProtoMessage()    {}
func (*RecommendItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_721ac0927679af21, []int{2}
}

func (m *RecommendItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendItem.Unmarshal(m, b)
}
func (m *RecommendItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendItem.Marshal(b, m, deterministic)
}
func (m *RecommendItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendItem.Merge(m, src)
}
func (m *RecommendItem) XXX_Size() int {
	return xxx_messageInfo_RecommendItem.Size(m)
}
func (m *RecommendItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendItem.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendItem proto.InternalMessageInfo

func (m *RecommendItem) GetMoiveId() int32 {
	if m != nil {
		return m.MoiveId
	}
	return 0
}

func (m *RecommendItem) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func init() {
	proto.RegisterType((*RecommendReq)(nil), "RecommendPro.RecommendReq")
	proto.RegisterType((*RecommendReply)(nil), "RecommendPro.RecommendReply")
	proto.RegisterType((*RecommendItem)(nil), "RecommendPro.RecommendItem")
}

func init() { proto.RegisterFile("recommed_rpc.proto", fileDescriptor_721ac0927679af21) }

var fileDescriptor_721ac0927679af21 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4a, 0x4d, 0xce,
	0xcf, 0xcd, 0x4d, 0x4d, 0x89, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x09, 0x82, 0x88, 0xe5, 0xa5, 0x04, 0x14, 0xe5, 0x2b, 0xa9, 0x71, 0x21, 0xf8, 0x41, 0xa9, 0x85,
	0x42, 0x62, 0x5c, 0x6c, 0xa5, 0xc5, 0xa9, 0x45, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac,
	0x41, 0x50, 0x9e, 0x52, 0x30, 0x17, 0x1f, 0x92, 0xba, 0x82, 0x9c, 0x4a, 0x21, 0x47, 0x2e, 0xde,
	0x22, 0x98, 0x88, 0x67, 0x49, 0x6a, 0xae, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xb4, 0x1e,
	0xb2, 0xf9, 0x08, 0x0e, 0x48, 0x49, 0x10, 0xaa, 0x0e, 0x25, 0x47, 0x2e, 0x5e, 0x14, 0x79, 0x21,
	0x09, 0x2e, 0xf6, 0xdc, 0xfc, 0xcc, 0xb2, 0x54, 0xb8, 0xf5, 0x30, 0x2e, 0xc8, 0x5d, 0x45, 0x89,
	0x25, 0x99, 0x79, 0xe9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x4c, 0x41, 0x50, 0x9e, 0x51, 0x08, 0x17,
	0x27, 0xdc, 0x08, 0x21, 0x77, 0x64, 0x8e, 0x14, 0x0e, 0x87, 0x04, 0xa5, 0x16, 0x4a, 0xc9, 0xe0,
	0x94, 0x2b, 0xc8, 0xa9, 0x54, 0x62, 0x48, 0x62, 0x03, 0x07, 0x95, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x72, 0xf5, 0x29, 0x41, 0x40, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecommendClient is the client API for Recommend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecommendClient interface {
	// Sends a greeting
	Recommend(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (*RecommendReply, error)
}

type recommendClient struct {
	cc *grpc.ClientConn
}

func NewRecommendClient(cc *grpc.ClientConn) RecommendClient {
	return &recommendClient{cc}
}

func (c *recommendClient) Recommend(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (*RecommendReply, error) {
	out := new(RecommendReply)
	err := c.cc.Invoke(ctx, "/RecommendPro.Recommend/Recommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendServer is the server API for Recommend service.
type RecommendServer interface {
	// Sends a greeting
	Recommend(context.Context, *RecommendReq) (*RecommendReply, error)
}

// UnimplementedRecommendServer can be embedded to have forward compatible implementations.
type UnimplementedRecommendServer struct {
}

func (*UnimplementedRecommendServer) Recommend(ctx context.Context, req *RecommendReq) (*RecommendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recommend not implemented")
}

func RegisterRecommendServer(s *grpc.Server, srv RecommendServer) {
	s.RegisterService(&_Recommend_serviceDesc, srv)
}

func _Recommend_Recommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServer).Recommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendPro.Recommend/Recommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServer).Recommend(ctx, req.(*RecommendReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Recommend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RecommendPro.Recommend",
	HandlerType: (*RecommendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recommend",
			Handler:    _Recommend_Recommend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommed_rpc.proto",
}
