# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommed_rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommed_rpc.proto',
  package='RecommendPro',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12recommed_rpc.proto\x12\x0cRecommendPro\"\x1e\n\x0cRecommendReq\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"D\n\x0eRecommendReply\x12\x32\n\rrecommendItem\x18\x01 \x03(\x0b\x32\x1b.RecommendPro.RecommendItem\"0\n\rRecommendItem\x12\x0f\n\x07moiveId\x18\x01 \x01(\x05\x12\x0e\n\x06rating\x18\x02 \x01(\x02\x32T\n\tRecommend\x12G\n\tRecommend\x12\x1a.RecommendPro.RecommendReq\x1a\x1c.RecommendPro.RecommendReply\"\x00\x62\x06proto3'
)




_RECOMMENDREQ = _descriptor.Descriptor(
  name='RecommendReq',
  full_name='RecommendPro.RecommendReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='RecommendPro.RecommendReq.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=66,
)


_RECOMMENDREPLY = _descriptor.Descriptor(
  name='RecommendReply',
  full_name='RecommendPro.RecommendReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendItem', full_name='RecommendPro.RecommendReply.recommendItem', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=136,
)


_RECOMMENDITEM = _descriptor.Descriptor(
  name='RecommendItem',
  full_name='RecommendPro.RecommendItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='moiveId', full_name='RecommendPro.RecommendItem.moiveId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='RecommendPro.RecommendItem.rating', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=186,
)

_RECOMMENDREPLY.fields_by_name['recommendItem'].message_type = _RECOMMENDITEM
DESCRIPTOR.message_types_by_name['RecommendReq'] = _RECOMMENDREQ
DESCRIPTOR.message_types_by_name['RecommendReply'] = _RECOMMENDREPLY
DESCRIPTOR.message_types_by_name['RecommendItem'] = _RECOMMENDITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecommendReq = _reflection.GeneratedProtocolMessageType('RecommendReq', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDREQ,
  '__module__' : 'recommed_rpc_pb2'
  # @@protoc_insertion_point(class_scope:RecommendPro.RecommendReq)
  })
_sym_db.RegisterMessage(RecommendReq)

RecommendReply = _reflection.GeneratedProtocolMessageType('RecommendReply', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDREPLY,
  '__module__' : 'recommed_rpc_pb2'
  # @@protoc_insertion_point(class_scope:RecommendPro.RecommendReply)
  })
_sym_db.RegisterMessage(RecommendReply)

RecommendItem = _reflection.GeneratedProtocolMessageType('RecommendItem', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDITEM,
  '__module__' : 'recommed_rpc_pb2'
  # @@protoc_insertion_point(class_scope:RecommendPro.RecommendItem)
  })
_sym_db.RegisterMessage(RecommendItem)



_RECOMMEND = _descriptor.ServiceDescriptor(
  name='Recommend',
  full_name='RecommendPro.Recommend',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=188,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recommend',
    full_name='RecommendPro.Recommend.Recommend',
    index=0,
    containing_service=None,
    input_type=_RECOMMENDREQ,
    output_type=_RECOMMENDREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMEND)

DESCRIPTOR.services_by_name['Recommend'] = _RECOMMEND

# @@protoc_insertion_point(module_scope)
